export const zhCN = {
  appName: 'AI 职位匹配助手',
  navigationLabel: '招聘评估工作台',
  navigation: {
    ariaLabel: '主要功能',
    home: '首页',
    assistant: '职位匹配',
    resume: '简历预览',
    contact: '联系候选人',
    returnToConversation: '返回当前匹配',
  },
  brandMark: '梅',
  demoChip: 'Mock MVP',
  hero: {
    eyebrow: '固定候选人 · 梅唱',
    title: 'AI 职位匹配助手',
    introduction:
      '基于候选人真实简历，帮助招聘者快速核对岗位匹配证据。',
    scopeLabel: '产品范围说明',
    scopePoints: [
      '当前演示仅分析固定候选人梅唱',
      '区分明确证据、部分信息和信息缺失',
      '不生成总体评分，也不替代招聘决策',
    ],
  },
  conversation: {
    kicker: '固定候选人 · 梅唱',
    title: '职位匹配对话',
    description: '当前阶段使用确定性 Mock 响应验证完整交互。',
    ready: '助手已就绪',
    assistantName: 'AI 助手',
    userName: '招聘者',
    assistantAvatar: 'AI',
    userAvatar: '你',
    initialMessageLabel: '初始引导',
    jobDescriptionMessageLabel: '职位描述',
    matchingAnalysisMessageLabel: '匹配分析',
    followUpQuestionMessageLabel: '追问',
    followUpAnswerMessageLabel: '追问回答',
  },
  guidance: {
    title: '请提供完整的职位描述',
    content:
      '## 请提供完整的职位描述\n\n我会按职位要求整理候选人简历中的**明确证据**、**部分信息**和**缺失信息**。\n\n- 不生成候选人评分\n- 不作录用判断\n- 不补充简历中没有的信息',
  },
  jobDescription: {
    title: '粘贴职位描述，开始匹配',
    description: '建议包含岗位职责、必要能力和加分项，以便后续真实分析覆盖关键要求。',
    label: '职位描述',
    placeholder: '粘贴完整职位描述（建议包含职责与要求）',
    useExample: '使用示例',
    viewExampleReport: '立即查看示例报告',
    submit: '开始分析',
    submitting: '正在整理证据…',
    characterCount: (count: number) => `${count} / 6000 字符`,
    emptyError: '请先输入职位描述。',
    shortError: '职位描述过短，请至少输入 40 个字符，以便识别有效的岗位要求。',
  },
  loading: {
    title: '正在生成匹配报告',
    typicalDuration: '通常需要约 30–60 秒',
    elapsed: (seconds: number) => `已等待 ${seconds} 秒`,
    extendedWait: '复杂岗位可能需要更长时间，请继续等待。',
  },
  failure: {
    title: '暂时无法生成报告',
    description: '本次处理没有完成。你的职位描述仍然保留，可以重新尝试。',
    invalidRequest: '后端未接受这份职位描述。请检查内容后重新提交。',
    aiUnavailable: 'AI 服务暂时不可用。你的职位描述仍然保留，可以重新尝试。',
    retry: '重新尝试',
  },
  report: {
    startOver: '分析新的职位',
    viewResume: '查看简历',
    contactCandidate: '联系候选人',
    giveFeedback: '提交反馈',
    mockNoticeTitle: 'Mock AI 演示',
    mockNoticeBody: '此报告由后端确定性 Mock AI 服务生成，用于验证完整产品流程。',
    exampleModeLabel: '示例报告',
    exampleFollowUpTitle: '示例模式不支持追问',
    exampleFollowUpDescription: '提交你自己的职位描述并生成正式报告后，可以继续追问。',
    submitOwnJobDescription: '提交自己的 JD',
  },
  resume: {
    kicker: '固定候选人资料',
    title: '梅唱的简历',
    description: '预览或下载本次匹配分析所使用的同一份、未经修改的 PDF 简历。',
    download: '下载 PDF',
    previewTitle: '梅唱的简历 PDF 预览',
  },
  contact: {
    kicker: '联系候选人',
    title: '联系梅唱',
    description: '联系方式来自候选人批准的简历。你可以填写姓名并复制问候语。',
    methodsLabel: '联系方式',
    emailLabel: '邮箱',
    phoneLabel: '电话',
    email: 'hisunnymay@163.com',
    phone: '18810675122',
    copyEmail: '复制邮箱',
    copyPhone: '复制电话',
    recruiterNameLabel: '您的称呼（可选）',
    recruiterNamePlaceholder: '请输入您的姓名，例如：张经理',
    recruiterNameFallback: '招聘负责人',
    greetingLabel: '问候语预览',
    greeting: (name: string) =>
      `您好梅唱，我是${name}。\n\n我们目前有一个岗位机会，对您的背景很感兴趣，想进一步了解您的经历。\n\n—— ${name}`,
    copyGreeting: '复制联系话术',
    copySuccess: '已复制',
    copyError: '复制失败，请手动选择问候语。',
    noAutoSend: '系统不会代表您自动发送任何消息。',
  },
  feedback: {
    actionsLabel: '报告操作与反馈',
    helpful: '回答有帮助',
    notHelpful: '回答没有帮助',
    kicker: '报告反馈',
    title: '这份匹配报告有帮助吗？',
    description: '反馈会与当前匹配报告关联，用于后续产品评估。提交完全自愿。',
    ratingLabel: '报告帮助程度',
    ratingOption: (rating: number) => `${rating} 分`,
    ratingRequired: '请选择 1–5 分后再提交。',
    dialogTitle: (rating: 1 | 5) =>
      rating === 5 ? '这份回答哪里有帮助？' : '这份回答哪里需要改进？',
    dialogDescription: '请选择反馈原因或填写具体反馈，帮助我们改进后续匹配分析。',
    optionsLabel: '请选择反馈原因（可多选）',
    predefinedOptions: (rating: 1 | 5) =>
      rating === 5
        ? [
            '证据清晰可核验',
            '覆盖了关键岗位要求',
            '信息缺口标注清楚',
            '结论简洁易用',
          ]
        : [
            '证据与结论对应不清',
            '遗漏关键岗位要求',
            '信息缺口不明确',
            '内容过于冗长',
          ],
    commentLabel: '或者填写具体反馈',
    commentPlaceholder: '请说明哪些内容有帮助，或还需要改进什么……',
    contributionRequired: '请选择至少一个原因，或填写具体反馈。',
    selectedReasonsPrefix: '选择项：',
    customFeedbackPrefix: '补充：',
    cancel: '取消',
    submit: '提交反馈',
    submitting: '正在提交…',
    successTitle: '反馈已提交',
    successDescription: '反馈已保存',
    reportNotFound: '未找到对应报告，请重新生成匹配报告后再提交。',
    submitError: '反馈暂时无法提交，请稍后重试。',
  },
  followUp: {
    label: '追问或补充信息',
    placeholder: '追问或补充信息，获取更精准的匹配分析……',
    send: '发送',
    sending: '发送中',
    unavailable: '生成匹配报告后可以继续追问。',
    invalidQuestion: '请输入 1 至 1000 个字符的问题。',
    loadingTitle: '正在回答追问',
    loadingDescription: '正在结合职位描述、匹配报告和当前对话整理回答。',
    failureTitle: '暂时无法回答追问',
    failureDescription: '这条问题仍然保留，可以在当前对话中重新尝试。',
    conversationNotFound: '当前匹配对话已不可用，请重新生成匹配报告。',
    aiUnavailable: 'AI 服务暂时不可用，可以重新尝试这条问题。',
    persistenceError: '本次追问未能保存，可以重新尝试这条问题。',
    retry: '重新尝试',
  },
  sampleJobDescription:
    '我们正在招聘一名 AI 产品经理，负责大模型产品从需求分析、方案设计、PRD 到研发落地和持续迭代。候选人需要具备 LLM 应用、Prompt 与模型评测经验，能够设计复杂 B 端业务流程并与研发团队高效协作。具备数据分析能力、API 调试或基础编程经验者优先，同时希望候选人能够说明产品上线后的量化业务结果。',
} as const
